Id: NaturalPoint.TrackIR # publisher.package format
Publisher: NaturalPoint
Name: TrackIR
AppMoniker: trackir
Version: 5.4.2
License: © 2020 NaturalPoint Inc. 
Homepage: https://www.naturalpoint.com/trackir/
LicenseUrl: https://www.naturalpoint.com/trackir/terms/
Description:
  TrackIR provides optical head tracking for various games and applications.
  This is the client application and driver package and requires you to have
  the TrackIR hardware before it will function correctly.
MinOSVersion: 6.0.0.0
InstallerType: exe
Installers:
  - Arch: x86
    Url: https://s3.amazonaws.com/naturalpoint/trackir/software/TrackIR_5.4.2.exe
    Sha256: 6AFED7ED4C3E4C00462930692D2DF232DF6E6D4EFD9DE57512301E48124BA058
    Switches:
      Silent: /s /a /s /v"/qb"
ManifestVersion: 0.1.0
